//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYS2015Data.Models.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities_History
    {
        public long ActivityHistoryID { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string AddedBy { get; set; }
        public string Details { get; set; }
        public long ActivityID { get; set; }
        public Nullable<long> ActivityItemID { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Activities_Items Activities_Items { get; set; }
    }
}
