//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYS2015Data.Models.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities_Items_UserAssociations
    {
        public long ItemAssociationID { get; set; }
        public System.Guid UserID { get; set; }
        public long ActivityItemID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> Duration { get; set; }
        public Nullable<bool> WasOnSite { get; set; }
        public Nullable<System.DateTime> Overtime { get; set; }
        public Nullable<System.DateTime> Doubletime { get; set; }
        public string UserEmail { get; set; }
        public string AssignedUserMobile { get; set; }
        public Nullable<System.DateTime> TravelTime { get; set; }
        public Nullable<System.DateTime> BreakTime { get; set; }
        public Nullable<System.DateTime> CalloutTime { get; set; }
        public Nullable<System.DateTime> MilesTime { get; set; }
        public Nullable<System.DateTime> KmTime { get; set; }
        public Nullable<System.DateTime> Time1_25 { get; set; }
        public Nullable<System.DateTime> Time1_5 { get; set; }
        public Nullable<System.DateTime> Time1_75 { get; set; }
        public Nullable<System.DateTime> Time2_0 { get; set; }
        public Nullable<System.DateTime> Time2_25 { get; set; }
        public Nullable<System.DateTime> Time2_5 { get; set; }
        public Nullable<decimal> Miles { get; set; }
        public Nullable<decimal> KM { get; set; }
    
        public virtual Activities_Items Activities_Items { get; set; }
    }
}
