//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYS2015Data.Models.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities_Items_Types
    {
        public Activities_Items_Types()
        {
            this.Activities_Items = new HashSet<Activities_Items>();
            this.JobRequests = new HashSet<JobRequest>();
        }
    
        public int ActivityItemTypeID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> ProposedDuration { get; set; }
        public Nullable<System.Guid> LayoutGuid { get; set; }
        public Nullable<long> TemplateQuoteID { get; set; }
        public string icon { get; set; }
        public string iconColor { get; set; }
        public string DefaultJobText { get; set; }
        public Nullable<long> NormalLabourChargeStockID { get; set; }
        public Nullable<long> TravelChargeStockID { get; set; }
        public Nullable<long> OutOfHoursLabourChargeStockID { get; set; }
        public Nullable<long> CalloutChargeStockID { get; set; }
        public Nullable<decimal> FixedPrice { get; set; }
        public Nullable<long> MilesChargeStockID { get; set; }
        public Nullable<long> KmChargeStockID { get; set; }
        public Nullable<long> Charge1_25StockID { get; set; }
        public Nullable<long> Charge1_5StockID { get; set; }
        public Nullable<long> Charge1_75StockID { get; set; }
        public Nullable<long> Charge2_0StockID { get; set; }
        public Nullable<long> Charge2_25StockID { get; set; }
        public Nullable<long> Charge2_5StockID { get; set; }
    
        public virtual ICollection<Activities_Items> Activities_Items { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual Stock Stock1 { get; set; }
        public virtual Stock Stock2 { get; set; }
        public virtual Stock Stock3 { get; set; }
        public virtual Stock Stock4 { get; set; }
        public virtual Stock Stock5 { get; set; }
        public virtual Stock Stock6 { get; set; }
        public virtual Stock Stock7 { get; set; }
        public virtual Stock Stock8 { get; set; }
        public virtual Stock Stock9 { get; set; }
        public virtual Stock Stock10 { get; set; }
        public virtual Stock Stock11 { get; set; }
        public virtual ICollection<JobRequest> JobRequests { get; set; }
    }
}
