//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYS2015Data.Models.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities_Items
    {
        public Activities_Items()
        {
            this.Activities_History = new HashSet<Activities_History>();
            this.Activities_Items_Assets = new HashSet<Activities_Items_Assets>();
            this.Activities_Items_CustomFormDetails = new HashSet<Activities_Items_CustomFormDetails>();
            this.Activities_Items_ServiceListItems = new HashSet<Activities_Items_ServiceListItems>();
            this.Activities_Items_UserAssociations = new HashSet<Activities_Items_UserAssociations>();
            this.Documents = new HashSet<Document>();
            this.HistoryNotes = new HashSet<HistoryNote>();
            this.JobRequests = new HashSet<JobRequest>();
            this.Quotes_Items = new HashSet<Quotes_Items>();
            this.ToDoListItems = new HashSet<ToDoListItem>();
        }
    
        public long ActivityItemID { get; set; }
        public long ActivityID { get; set; }
        public Nullable<System.Guid> AssetID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<long> StockID { get; set; }
        public Nullable<System.DateTime> ProposedDate { get; set; }
        public Nullable<System.DateTime> ProposedDuration { get; set; }
        public Nullable<System.DateTime> ActualDuration { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public Nullable<System.Guid> AssignedUser { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ActivityItemTypeID { get; set; }
        public bool IsComplete { get; set; }
        public long QuoteID { get; set; }
        public Nullable<int> UserSkillSetID { get; set; }
        public Nullable<System.DateTime> SLAExpiryTime { get; set; }
        public Nullable<System.DateTime> ActivityItemCompletionTime { get; set; }
        public string Signature1 { get; set; }
        public string Signature2 { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public string Spare1 { get; set; }
        public string Spare2 { get; set; }
        public string Spare3 { get; set; }
        public string Spare4 { get; set; }
        public string Spare5 { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<bool> InActive { get; set; }
        public string AssignedUserName { get; set; }
        public Nullable<bool> NextServiceDateBooked { get; set; }
        public Nullable<bool> NeedsNewServiceDate { get; set; }
        public Nullable<bool> ShowInScheduler { get; set; }
        public Nullable<bool> Paid { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<System.DateTime> TravelTime { get; set; }
        public Nullable<System.DateTime> BreakTime { get; set; }
        public Nullable<bool> IsQuote { get; set; }
        public Nullable<bool> IsChargeable { get; set; }
        public Nullable<long> OriginatingRequestID { get; set; }
        public string UserDefinedReference { get; set; }
        public string PrintName1 { get; set; }
        public string PrintName2 { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public Nullable<System.DateTime> Overtime { get; set; }
        public string CustomerOrderNumber { get; set; }
        public Nullable<System.DateTime> DueBy { get; set; }
        public Nullable<System.Guid> RelatedJobID { get; set; }
        public Nullable<System.DateTime> CalloutTime { get; set; }
        public Nullable<System.DateTime> DoubleTime { get; set; }
        public Nullable<int> Fault1ID { get; set; }
        public Nullable<int> Fault2ID { get; set; }
        public Nullable<int> Fault3ID { get; set; }
        public Nullable<int> Fault4ID { get; set; }
        public Nullable<bool> Reviewed { get; set; }
        public Nullable<bool> LeadGenerated { get; set; }
        public string AssignedUserEmail { get; set; }
        public string AssignedUserMobile { get; set; }
        public string ActivityItemName { get; set; }
        public string ActivityItemDetails { get; set; }
        public string FurtherworksDesc { get; set; }
        public Nullable<System.DateTime> MilesTime { get; set; }
        public Nullable<System.DateTime> KmTime { get; set; }
        public Nullable<System.DateTime> Time1_25 { get; set; }
        public Nullable<System.DateTime> Time1_5 { get; set; }
        public Nullable<System.DateTime> Time1_75 { get; set; }
        public Nullable<System.DateTime> Time2_0 { get; set; }
        public Nullable<System.DateTime> Time2_25 { get; set; }
        public Nullable<System.DateTime> Time2_5 { get; set; }
        public Nullable<decimal> Miles { get; set; }
        public Nullable<decimal> KM { get; set; }
        public string PONumber { get; set; }
        public string DropboxLink1 { get; set; }
        public string DropboxLink2 { get; set; }
        public string DropboxLink3 { get; set; }
        public string DropboxLink4 { get; set; }
        public Nullable<long> ContractID { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual ICollection<Activities_History> Activities_History { get; set; }
        public virtual Activities_Items_Status Activities_Items_Status { get; set; }
        public virtual Activities_Items_Types Activities_Items_Types { get; set; }
        public virtual Asset Asset { get; set; }
        public virtual ICollection<Activities_Items_Assets> Activities_Items_Assets { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Activities_Items_CustomFormDetails> Activities_Items_CustomFormDetails { get; set; }
        public virtual JobRequest JobRequest { get; set; }
        public virtual Quote Quote { get; set; }
        public virtual ICollection<Activities_Items_ServiceListItems> Activities_Items_ServiceListItems { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual ICollection<Activities_Items_UserAssociations> Activities_Items_UserAssociations { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<HistoryNote> HistoryNotes { get; set; }
        public virtual ICollection<JobRequest> JobRequests { get; set; }
        public virtual ICollection<Quotes_Items> Quotes_Items { get; set; }
        public virtual ICollection<ToDoListItem> ToDoListItems { get; set; }
    }
}
