//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYS2015Data.Models.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities_Items_CustomFormDetails
    {
        public Activities_Items_CustomFormDetails()
        {
            this.Activities_Items_CustomFieldDetails = new HashSet<Activities_Items_CustomFieldDetails>();
        }
    
        public System.Guid FormID { get; set; }
        public long ActivityItemID { get; set; }
        public bool ShowTitle { get; set; }
        public int TitleX { get; set; }
        public int TitleY { get; set; }
        public double TitleH { get; set; }
        public double TitleW { get; set; }
        public string BackColor { get; set; }
        public int TitleSize { get; set; }
        public bool ShowLogo { get; set; }
        public int LogoX { get; set; }
        public int LogoY { get; set; }
        public double LogoH { get; set; }
        public double LogoW { get; set; }
        public string TitleText { get; set; }
        public Nullable<bool> ShowOnCustPDF { get; set; }
        public Nullable<bool> ShowOnReceipt { get; set; }
        public Nullable<bool> JobSheet1 { get; set; }
        public Nullable<bool> JobSheet2 { get; set; }
        public Nullable<bool> JobSheet3 { get; set; }
        public Nullable<bool> AsInvoice { get; set; }
        public Nullable<bool> JobSheet4 { get; set; }
        public Nullable<int> PrefIndex { get; set; }
        public Nullable<bool> IsLandscape { get; set; }
        public Nullable<bool> IsMobileForm { get; set; }
        public Nullable<bool> ViewFormInJobDetails { get; set; }
        public Nullable<bool> IsQuoteForm { get; set; }
        public Nullable<bool> IsInvoiceForm { get; set; }
        public Nullable<bool> IsJobForm { get; set; }
        public Nullable<bool> IsReceiptForm { get; set; }
        public Nullable<int> ColumnNum { get; set; }
        public Nullable<bool> IsPurchaseForm { get; set; }
        public Nullable<int> SetCertNumber { get; set; }
        public Nullable<bool> IsSalesInvoiceForm { get; set; }
        public Nullable<bool> IsCreditForm { get; set; }
        public Nullable<decimal> FooterHeight { get; set; }
    
        public virtual Activities_Items Activities_Items { get; set; }
        public virtual ICollection<Activities_Items_CustomFieldDetails> Activities_Items_CustomFieldDetails { get; set; }
    }
}
