//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYS2015Data.Models.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities_Items_Assets
    {
        public long ActivitiesItemsAssetID { get; set; }
        public long ActivityItemID { get; set; }
        public System.Guid AssetID { get; set; }
        public bool Completed { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsFaulty { get; set; }
        public string FaultDescription { get; set; }
        public Nullable<bool> InActive { get; set; }
    
        public virtual Activities_Items Activities_Items { get; set; }
        public virtual Asset Asset { get; set; }
    }
}
