//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYS2015Data.Models.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities_Items_CustomFieldDetails
    {
        public Activities_Items_CustomFieldDetails()
        {
            this.Activities_Items_CustomFieldDetails1 = new HashSet<Activities_Items_CustomFieldDetails>();
        }
    
        public System.Guid FieldID { get; set; }
        public System.Guid FormID { get; set; }
        public int FieldX { get; set; }
        public int FieldY { get; set; }
        public double FieldH { get; set; }
        public double FieldW { get; set; }
        public int FontSize { get; set; }
        public byte[] Data { get; set; }
        public string Content { get; set; }
        public bool IsChecked { get; set; }
        public int FieldType { get; set; }
        public bool Required { get; set; }
        public Nullable<long> MobileOrder { get; set; }
        public Nullable<int> ColumnNum { get; set; }
        public string TableColumnID { get; set; }
        public Nullable<int> TableRowID { get; set; }
        public Nullable<long> CertNumberStartValue { get; set; }
        public Nullable<int> CertNumberIncrementValue { get; set; }
        public Nullable<bool> IsFooterField { get; set; }
        public Nullable<bool> IsLinkable { get; set; }
        public Nullable<System.Guid> LinkerID { get; set; }
        public Nullable<bool> IsLinked { get; set; }
    
        public virtual Activities_Items_CustomFormDetails Activities_Items_CustomFormDetails { get; set; }
        public virtual ICollection<Activities_Items_CustomFieldDetails> Activities_Items_CustomFieldDetails1 { get; set; }
        public virtual Activities_Items_CustomFieldDetails Activities_Items_CustomFieldDetails2 { get; set; }
    }
}
