//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYS2015Data.Models.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.Activities_History = new HashSet<Activities_History>();
            this.Activities_Items = new HashSet<Activities_Items>();
            this.Assets_ServiceHistory = new HashSet<Assets_ServiceHistory>();
            this.Documents = new HashSet<Document>();
            this.HistoryNotes = new HashSet<HistoryNote>();
        }
    
        public long ActivityID { get; set; }
        public Nullable<int> CustomerCref { get; set; }
        public string BillingPostalName { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingAddress3 { get; set; }
        public string BillingAddress4 { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingCountry { get; set; }
        public string BillingPostcode { get; set; }
        public Nullable<int> ClientCref { get; set; }
        public string ActivityPostalName { get; set; }
        public string ActivityAddress1 { get; set; }
        public string ActivityAddress2 { get; set; }
        public string ActivityAddress3 { get; set; }
        public string ActivityAddress4 { get; set; }
        public string ActivityCity { get; set; }
        public string ActivityState { get; set; }
        public string ActivityCountry { get; set; }
        public string ActivityPostcode { get; set; }
        public string CustomerContact { get; set; }
        public string CustomerContactTel { get; set; }
        public string CustomerContactEmail { get; set; }
        public string ActivityContact { get; set; }
        public string ActivityContactTel { get; set; }
        public string ActivityContactEmail { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> ActivityTypeID { get; set; }
        public string Details { get; set; }
        public Nullable<double> CustomerLongitude { get; set; }
        public Nullable<double> CustomerLatitude { get; set; }
        public Nullable<double> ClientLongitude { get; set; }
        public Nullable<double> ClientLatitude { get; set; }
        public string Spare1 { get; set; }
        public string Spare2 { get; set; }
        public string Spare3 { get; set; }
        public string Spare4 { get; set; }
        public Nullable<System.DateTime> SpateDT1 { get; set; }
        public Nullable<System.DateTime> SpareDT2 { get; set; }
        public Nullable<System.DateTime> SpareDT3 { get; set; }
        public Nullable<System.DateTime> SpareDT4 { get; set; }
        public Nullable<int> SpareInt1 { get; set; }
        public Nullable<int> SpareInt2 { get; set; }
        public Nullable<int> SpareInt3 { get; set; }
        public Nullable<int> SpareInt4 { get; set; }
        public Nullable<bool> SpareBool1 { get; set; }
        public Nullable<bool> SpareBool2 { get; set; }
        public Nullable<bool> SpareBool3 { get; set; }
        public Nullable<bool> SpareBool4 { get; set; }
        public bool ChargeCustomer { get; set; }
        public Nullable<System.DateTime> SLAExpiryTime { get; set; }
        public Nullable<System.DateTime> ActivityCompletionTime { get; set; }
        public Nullable<decimal> EstJobCost { get; set; }
        public Nullable<bool> InActive { get; set; }
        public Nullable<bool> Complete { get; set; }
        public string UserDefinedReference { get; set; }
        public Nullable<int> ProjectID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual ICollection<Activities_History> Activities_History { get; set; }
        public virtual ICollection<Activities_Items> Activities_Items { get; set; }
        public virtual ICollection<Assets_ServiceHistory> Assets_ServiceHistory { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<HistoryNote> HistoryNotes { get; set; }
    }
}
