//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYS2015Data.Models.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities_Items_ServiceListItems
    {
        public long ServiceListID { get; set; }
        public long ActivityItemID { get; set; }
        public long AssetPartID { get; set; }
        public bool Serviced { get; set; }
        public bool Replaced { get; set; }
        public string ReplacementSerial { get; set; }
        public string OriginalSerial { get; set; }
        public Nullable<System.DateTime> DateServiced { get; set; }
        public Nullable<bool> IsFaulty { get; set; }
        public string FaultDescription { get; set; }
        public Nullable<bool> InActive { get; set; }
    
        public virtual Activities_Items Activities_Items { get; set; }
        public virtual Assets_Parts Assets_Parts { get; set; }
    }
}
