//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYS2015Data.Models.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities_Items_Status
    {
        public Activities_Items_Status()
        {
            this.Activities_Items = new HashSet<Activities_Items>();
        }
    
        public int ActivityItemStatusID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Activities_Items> Activities_Items { get; set; }
    }
}
