//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYS2015Data.Models.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assets_SubTypes
    {
        public Assets_SubTypes()
        {
            this.Assets = new HashSet<Asset>();
        }
    
        public int AssetSubTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Asset> Assets { get; set; }
    }
}
