//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYS2015Data.Models.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assets_ServiceHistory
    {
        public long ServiceHistoryID { get; set; }
        public System.Guid AssetID { get; set; }
        public System.DateTime ServiceDate { get; set; }
        public string Details { get; set; }
        public Nullable<long> ActivityID { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Asset Asset { get; set; }
    }
}
