//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYS2015Data.Models.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_Parts_History
    {
        public int HistoryID { get; set; }
        public long AssetPartID { get; set; }
        public string Details { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string AddedBy { get; set; }
    
        public virtual Assets_Parts Assets_Parts { get; set; }
    }
}
