//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYS2015Data.Models.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assets_Parts
    {
        public Assets_Parts()
        {
            this.Activities_Items_ServiceListItems = new HashSet<Activities_Items_ServiceListItems>();
            this.Asset_Parts_History = new HashSet<Asset_Parts_History>();
            this.Documents = new HashSet<Document>();
            this.HistoryNotes = new HashSet<HistoryNote>();
            this.JobRequest_Parts = new HashSet<JobRequest_Parts>();
            this.Quotes_Items = new HashSet<Quotes_Items>();
            this.Quotes_Items1 = new HashSet<Quotes_Items>();
        }
    
        public long AssetPartID { get; set; }
        public Nullable<System.Guid> AssetID { get; set; }
        public Nullable<long> StockItemID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string AssetLocale { get; set; }
        public Nullable<int> WeightMeasure { get; set; }
        public Nullable<int> DimensionMeasure { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Depth { get; set; }
        public Nullable<double> ExtHeight { get; set; }
        public Nullable<double> ExtWidth { get; set; }
        public Nullable<double> ExtDepth { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> ExtWeight { get; set; }
        public Nullable<int> CustomerRating { get; set; }
        public string SerialNumber { get; set; }
        public string Barcode1 { get; set; }
        public string Barcode2 { get; set; }
        public string Barcode3 { get; set; }
        public string Barcode4 { get; set; }
        public string Barcode5 { get; set; }
        public string RFID1 { get; set; }
        public string RFID2 { get; set; }
        public string RFID3 { get; set; }
        public string RFID4 { get; set; }
        public string RFID5 { get; set; }
        public Nullable<System.DateTime> Warranty1Start { get; set; }
        public Nullable<System.DateTime> Warranty1End { get; set; }
        public Nullable<System.DateTime> Warranty2Start { get; set; }
        public Nullable<System.DateTime> Warranty2End { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public Nullable<System.DateTime> RemovalDate { get; set; }
        public bool Enabled { get; set; }
        public Nullable<bool> OnRepair { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<double> CurrentPrice { get; set; }
        public Nullable<bool> CalculateDep { get; set; }
        public Nullable<double> DepPercentage { get; set; }
        public Nullable<int> PeriodDep { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<long> ImageID { get; set; }
        public string ImageName { get; set; }
        public Nullable<long> Image2ID { get; set; }
        public string ImageName2 { get; set; }
        public Nullable<long> Image3ID { get; set; }
        public string ImageName3 { get; set; }
        public Nullable<long> Image4ID { get; set; }
        public string ImageName4 { get; set; }
        public Nullable<long> Image5ID { get; set; }
        public string ImageName5 { get; set; }
        public Nullable<long> Image6ID { get; set; }
        public string ImageName6 { get; set; }
        public string ModelName { get; set; }
        public string ModelData { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string LastupdatedBy { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> SpareDT1 { get; set; }
        public Nullable<System.DateTime> SpareDT2 { get; set; }
        public Nullable<System.DateTime> SpareDT3 { get; set; }
        public Nullable<System.DateTime> SpareDT4 { get; set; }
        public string SpareText1 { get; set; }
        public string SpareText2 { get; set; }
        public string SpareText3 { get; set; }
        public string SpareText4 { get; set; }
        public Nullable<int> SpareInt1 { get; set; }
        public Nullable<int> SpareInt2 { get; set; }
        public Nullable<int> SpareInt3 { get; set; }
        public Nullable<int> SpareInt4 { get; set; }
        public Nullable<bool> SpareBool1 { get; set; }
        public Nullable<bool> SpareBool2 { get; set; }
        public Nullable<bool> SpareBool3 { get; set; }
        public Nullable<bool> SpareBool4 { get; set; }
        public Nullable<bool> InActive { get; set; }
        public Nullable<bool> DisallowMobile { get; set; }
    
        public virtual ICollection<Activities_Items_ServiceListItems> Activities_Items_ServiceListItems { get; set; }
        public virtual ICollection<Asset_Parts_History> Asset_Parts_History { get; set; }
        public virtual Asset Asset { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<HistoryNote> HistoryNotes { get; set; }
        public virtual ICollection<JobRequest_Parts> JobRequest_Parts { get; set; }
        public virtual ICollection<Quotes_Items> Quotes_Items { get; set; }
        public virtual ICollection<Quotes_Items> Quotes_Items1 { get; set; }
    }
}
