//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYS2015Data.Models.Company
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MindYourServiceEntities : DbContext
    {
        public MindYourServiceEntities()
            : base("name=MindYourServiceEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Activities_History> Activities_History { get; set; }
        public virtual DbSet<Activities_Items> Activities_Items { get; set; }
        public virtual DbSet<Activities_Items_Assets> Activities_Items_Assets { get; set; }
        public virtual DbSet<Activities_Items_CustomFieldDetails> Activities_Items_CustomFieldDetails { get; set; }
        public virtual DbSet<Activities_Items_CustomFormDetails> Activities_Items_CustomFormDetails { get; set; }
        public virtual DbSet<Activities_Items_ServiceListItems> Activities_Items_ServiceListItems { get; set; }
        public virtual DbSet<Activities_Items_Status> Activities_Items_Status { get; set; }
        public virtual DbSet<Activities_Items_Types> Activities_Items_Types { get; set; }
        public virtual DbSet<Activities_Items_UserAssociations> Activities_Items_UserAssociations { get; set; }
        public virtual DbSet<Asset_Parts_History> Asset_Parts_History { get; set; }
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<Assets_History> Assets_History { get; set; }
        public virtual DbSet<Assets_Parts> Assets_Parts { get; set; }
        public virtual DbSet<Assets_ServiceHistory> Assets_ServiceHistory { get; set; }
        public virtual DbSet<Assets_SubTypes> Assets_SubTypes { get; set; }
        public virtual DbSet<Assets_Types> Assets_Types { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Documents_Data> Documents_Data { get; set; }
        public virtual DbSet<HistoryNote> HistoryNotes { get; set; }
        public virtual DbSet<JobRequest_Assets> JobRequest_Assets { get; set; }
        public virtual DbSet<JobRequest_Parts> JobRequest_Parts { get; set; }
        public virtual DbSet<JobRequest> JobRequests { get; set; }
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<Quotes_Items> Quotes_Items { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<TaxCode> TaxCodes { get; set; }
        public virtual DbSet<ToDoListItem> ToDoListItems { get; set; }
    }
}
