//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYS2015Data.Models.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public Quote()
        {
            this.Activities_Items = new HashSet<Activities_Items>();
            this.Quotes_Items = new HashSet<Quotes_Items>();
        }
    
        public long ActivityQuoteID { get; set; }
        public System.DateTime QuoteDate { get; set; }
        public string ERPRef { get; set; }
        public Nullable<System.DateTime> QuoteExpiry { get; set; }
        public Nullable<long> SalesOrderID { get; set; }
        public string ERPQuoteNumber { get; set; }
    
        public virtual ICollection<Activities_Items> Activities_Items { get; set; }
        public virtual ICollection<Quotes_Items> Quotes_Items { get; set; }
    }
}
