//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYS2015Data.Models.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotes_Items
    {
        public long QuoteItemID { get; set; }
        public Nullable<long> StockID { get; set; }
        public decimal ItemPrice { get; set; }
        public bool PriceOverride { get; set; }
        public decimal Quantity { get; set; }
        public long QuoteID { get; set; }
        public string Description { get; set; }
        public Nullable<long> NewAssetPartID { get; set; }
        public Nullable<long> ReplacedAssetPartID { get; set; }
        public Nullable<int> TaxCodesID { get; set; }
        public Nullable<long> BinID { get; set; }
        public Nullable<bool> IsExpensesItem { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<System.DateTime> DateExpensePaid { get; set; }
        public string ExpensePaymentRef { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<decimal> ItemCost { get; set; }
        public Nullable<decimal> ItemMargin { get; set; }
        public Nullable<decimal> LabourCost { get; set; }
        public Nullable<decimal> LabourMargin { get; set; }
        public Nullable<decimal> LabourSellingPrice { get; set; }
        public Nullable<bool> NonChargeable { get; set; }
        public Nullable<bool> IsLabourItem { get; set; }
        public Nullable<bool> Consolidated { get; set; }
        public Nullable<long> OrderItemID { get; set; }
        public string UnitOfMeasureString { get; set; }
        public Nullable<int> ItemIndex { get; set; }
        public Nullable<long> ActivitiesItemID { get; set; }
        public Nullable<decimal> OriginalItemPrice { get; set; }
    
        public virtual Activities_Items Activities_Items { get; set; }
        public virtual Assets_Parts Assets_Parts { get; set; }
        public virtual Assets_Parts Assets_Parts1 { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Quote Quote { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual TaxCode TaxCode { get; set; }
    }
}
