//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYS2015Data.Models.Company
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxCode
    {
        public TaxCode()
        {
            this.Customers = new HashSet<Customer>();
            this.Quotes_Items = new HashSet<Quotes_Items>();
            this.Stocks = new HashSet<Stock>();
            this.Stocks1 = new HashSet<Stock>();
        }
    
        public int TaxCodeID { get; set; }
        public Nullable<bool> active { get; set; }
        public string reference { get; set; }
        public string reference2 { get; set; }
        public string type { get; set; }
        public string taxationCountry { get; set; }
        public string taxationLocale { get; set; }
        public Nullable<decimal> value { get; set; }
        public string valueText { get; set; }
        public Nullable<bool> primacyIndicator { get; set; }
        public string orderOfPrecedence { get; set; }
        public Nullable<System.Guid> ERPRef { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsSaleTaxCode { get; set; }
        public Nullable<bool> IsPurchaseTaxCode { get; set; }
        public string ERPTaxCodeNumber { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Quotes_Items> Quotes_Items { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual ICollection<Stock> Stocks1 { get; set; }
    }
}
